backend:
  name: github
  repo: benjgebob-bot/aurora-autohaus

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "config"
    label: "Site Configuration"
    files:
      - file: "index.html"
        label: "Startseite"
        fields:
          - {label: "Hero Titel", name: "title", widget: "string"}
          - {label: "Hero Bild", name: "hero_image", widget: "image"}
